### PR TITLE
Changed Button

### PR DESCRIPTION
**Pull request by nksmanya**
Solves issue #227 
Changed the inpur bar to this: 
image
From this:
Screenshot 2024-10-16 173529

### CODE REVIEW

**Review by PRathod27 — CHANGES_REQUESTED** [review]
Do provide border radius to the submit button.

**Comment by nksmanya** [comment]
image
Please check this and let me know if this needs any change.

**Comment by PRathod27** [comment]
@nksmanya Let us review it then you will be informed.

**Comment by soham0005** [comment]
@nksmanya there are some conflicts, please do resolve them and commit your changes again

**Pull request closed without merging**
