### PR TITLE
Improved Responsiveness

### PR DESCRIPTION
**Pull request by rishabhrawat05**
Hey! @soham0005 
The project Responsiveness has been updated #4 
Here's the changes 
1) Corrected alignment of elements for the desktop version
2) Made the website mobile friendly
3) Made a navbar differently for mobile devices

Here are some screenshots

Screenshot_2024_1005_093625
Screenshot_2024_1005_093631
Screenshot_2024_1005_093646
Screenshot_2024_1005_093656
Screenshot_2024_1005_093704
Screenshot_2024_1005_093717
Screenshot_2024_1005_093724
Screenshot_2024_1005_093732

### CODE REVIEW

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
@rishabhrawat05 it has some conflicts, please do solve those and push it again

**Comment by rishabhrawat05** [comment]
Hey! @soham0005 
I have resolved the conflicts

**Comment by rishabhrawat05** [comment]
Hey! @soham0005 
Is there any problem with the PR, it is not merged till yet

**Comment by PRathod27** [comment]
> Hey! @soham0005 Is there any problem with the PR, it is not merged till yet

Our Team is reviewing the changes. If changes are need to be made then our team will reach out to you.

**Review by PRathod27 — APPROVED** [review]

**Review by PayalKumari10 — APPROVED** [review]

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
@rishabhrawat05 The Navbar has been changed, so do pull the changes first.
You need to change the code for the responsiveness as well.
Please do the necessary changes and push the code again.
Feel free to reach out to us if you have any doubts

**Comment by rishabhrawat05** [comment]
Hi! @soham0005 
Conflict resolved

**Comment by PRathod27** [comment]
@rishabhrawat05 Till now, you have done a great job. But the make the photos responsive which are under the banner

Responsivenss
This three images.
This images are not being displayed properly. 
Please fix it.

**Comment by soham0005** [comment]
@rishabhrawat05 please do pull the changes first then make the updated PR, as there are some changes in the frontend

**Comment by rishabhrawat05** [comment]
Hey! @soham0005 @PRathod27 @PayalKumari10 
Can you check for any changes or  conflict with this updated pull request

**Pull request merged**
