### PR TITLE
i have designed the schema for backend..

### PR DESCRIPTION
**Pull request by SaanyaGarg5**
pls check and then give the feedback..
THANK YOU...

### CODE REVIEW

**Comment by soham0005** [comment]
Hello @SaanyaGarg5, The schema you have designed of User is already present and the backend functionality for User is already implemented, also the schema for Product and Order is not correct.
Please do connect on discord so that I can elaborate more on designing the schemas

**Comment by SaanyaGarg5** [comment]
i have done changes.. pls. check now

**Comment by SaanyaGarg5** [comment]
I have deleted the file.js and made changes in the code.. pls check..

**Comment by SaanyaGarg5** [comment]
i have made the changes.  .kindly check now

**Comment by SaanyaGarg5** [comment]
@soham0005  kindly merge and give me the points for my contribution

**Comment by SaanyaGarg5** [comment]
@soham0005  kindly add level 3, gssoc-ext , hacktoberfest

**Pull request closed without merging**
