### PR TITLE
Loginpage and SignUp page Added

### PR DESCRIPTION
**Pull request by Vishesh-Tripathi**
Login and SignUp Page added 
Screenshot 2024-10-05 185430
Screenshot 2024-10-05 185414

### CODE REVIEW

**Comment by soham0005** [comment]
@Vishesh-Tripathi Please attach the Postman/ thunderclient screenshot showing the API Request of register and login

**Comment by Vishesh-Tripathi** [comment]
Sure I will add it asap

**Comment by Vishesh-Tripathi** [comment]
> @Vishesh-Tripathi Please attach the Postman/ thunderclient screenshot showing the API Request of register and login

but you told me to use Dummy api

**Comment by Vishesh-Tripathi** [comment]
please elaborate what you want ?

**Comment by soham0005** [comment]
The API you have written should be tested locally, attach the screenshot of the API tested

**Comment by soham0005** [comment]
Hello @Vishesh-Tripathi , please do pull the code, as there have been some changes in the project and then make the PR again.
Do reach out if you have any doubts!

**Comment by Vishesh-Tripathi** [comment]
> Hello @Vishesh-Tripathi , please do pull the code, as there have been some changes in the project and then make the PR again.
> Do reach out if you have any doubts!

Ok

**Comment by soham0005** [comment]
@Vishesh-Tripathi your code isnt updated, please do pull the latest changes and then make your PR

**Comment by Vishesh-Tripathi** [comment]
Sorry for the delay there is an issue with my GitHub setup I will make a PR by today

**Comment by soham0005** [comment]
@Vishesh-Tripathi let me know once you are done

**Comment by Vishesh-Tripathi** [comment]
i Made a PR please review it

**Pull request closed without merging**
