### PR TITLE
UPDATED README FILE 

### PR DESCRIPTION
**Pull request by soham0028**
ISSUE : #168 
Hello @soham0005 
i have made all the necessary and promised changes please review the screenshots below : 

image
image
image

### CODE REVIEW

**Comment by soham0005** [comment]
Hello @soham0028, there are some conflicts, please do solve and push the changes again!

**Comment by soham0028** [comment]
hello do check the conflicts as i have resolved them kindly review and merge

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
@soham0028 Great Work!!
Happy Coding!

**Comment by soham0028** [comment]
thankyou

**Pull request merged**
