### PR TITLE
Fixed the Carousel navigation buttons and the text

### PR DESCRIPTION
**Pull request by 18Prachi**
Fix Issue #191 
This PR fixes the issue where the "Previous" and "Next" buttons were overlapping the carousel margins and ensures proper spacing between the buttons and the page edges. 

Changes made:
- Adjusted CSS for the button margin and background.
- Replaced circular button backgrounds with rounded rectangles to fit the "Previous" and "Next" text.
- Conditional rendering of `Carousel.Caption` to show only on the second slide.
- Fixed duplicate arrow signs appearing before the "Previous" and "Next" text.

Testing:
- Tested on both light and dark images.
- Buttons now properly spaced from the margin and display correctly.
- Verified on desktop and mobile views.

https://github.com/user-attachments/assets/5dbfe7cc-31b4-4755-b51e-3e6ab84b5a49

### CODE REVIEW

**Comment by soham0005** [comment]
Hello @18Prachi , there are some conflicts please do solve and commit your changes

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
Still there are some conflicts, please do have a look

**Comment by 18Prachi** [comment]
Can you please explain what conflicts are there as I am new to open
contributions and am not aware of these scenarios.

**Comment by soham0005** [comment]
connect on discord, i'll explain what conflicts you are facing

**Comment by 18Prachi** [comment]
Sure, can you share your id

**Comment by soham0005** [comment]
soham.215

**Comment by 18Prachi** [comment]
I have made the changes, you can check now.

**Comment by soham0005** [comment]
Still  not solved

**Comment by PRathod27** [comment]
@18Prachi Have you figured out the solution/

**Review by PRathod27 — APPROVED** [review]
the conflicts are resolved

**Pull request merged**
