### PR TITLE
Feature/bannerswipe

### PR DESCRIPTION
**Pull request by rahulvarma2005**
Screenshot 2024-10-06 135206
Screenshot 2024-10-06 135419

https://github.com/user-attachments/assets/97981c62-4f44-401b-89d0-3c0660d2e6a3

This pull request includes enhancements to the touch functionality for the `Banner` and `Slider` components, along with some styling updates. The main changes involve adding touch event handlers to improve the user experience on mobile devices and updating the CSS for better visual presentation.

Fixes: #48

### CODE REVIEW

**Comment by soham0005** [comment]
@rahulvarma2005 do attach the screenshot

**Comment by rahulvarma2005** [comment]
> @rahulvarma2005 do attach the screenshot

OK

**Comment by rahulvarma2005** [comment]
> @rahulvarma2005 do attach the screenshot

I have added the screenshot and video recording of the changes.
@soham0005

**Review by soham0005 — APPROVED** [review]

**Comment by rahulvarma2005** [comment]
@soham0005 Please add gssoc-ext, hacktoberfest-accepted, level2 tags

**Comment by soham0005** [comment]
@rahulvarma2005 once review is done, we'll label it dw

**Comment by soham0005** [comment]
@rahulvarma2005 there are some conflicts, please have a look and pull the latest changes then push your code

**Comment by rahulvarma2005** [comment]
@soham0005 please check it now.

**Comment by PRathod27** [comment]
@rahulvarma2005 There are conflicts in the code. The swiper is not working and active index is working properly. 
Do check it and make the changes.

**Comment by rahulvarma2005** [comment]
> @rahulvarma2005 There are conflicts in the code. The swiper is not working and active index is working properly. Do check it and make the changes.

Swiper option is only for touchscreen devices. It does not work on laptops/PCs.
May I know what exactly is not working please.

https://github.com/user-attachments/assets/c594040b-c0b7-41fe-a8c0-4c5c3d3a005a

**Comment by PRathod27** [comment]
@rahulvarma2005 Our team will again review it.

**Review by PRathod27 — APPROVED** [review]

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
@rahulvarma2005 ready to merge just ensure your code is upto date with the existing project code

**Comment by rahulvarma2005** [comment]
> @rahulvarma2005 ready to merge just ensure your code is upto date with the existing project code

Yes it is!

**Pull request merged**
