### PR TITLE
Added Contributor's Page

### PR DESCRIPTION
**Pull request by TBorundia**
Closes: #290 

I have added contributor's page that is directly fetching the data from the repo dynamically.

https://github.com/user-attachments/assets/62e54fa9-9e11-4780-8810-7d38a95622c5

### CODE REVIEW

**Comment by TBorundia** [comment]
@soham0005 @PRathod27 , I have opened new PR with the changes.
Please review it. Can you label it with level 3 for my work?
Thank You!!

**Comment by TBorundia** [comment]
@PRathod27 , Check it now Sir

**Comment by PRathod27** [comment]
> @PRathod27 , Check it now Sir

@TBorundia I'll merge It tomorrow. Or in case, other maintainers and PA will merge it.
Till now you have done a great work.
Happy Coding!

**Review by PRathod27 — APPROVED** [review]
Code is written in a good structured manner.

**Comment by TBorundia** [comment]
@PRathod27 , You have not assigned it and even not added the levels.
Can you please assign it with level 3 for my work.
Thank You!!

**Comment by PRathod27** [comment]
Ok let me correct it. Sorry for the inconvenience.

**Comment by PRathod27** [comment]
@TBorundia Labels have been added.
Thank you for your valuable contributions.
Happy Coding!

**Pull request merged**
