### PR TITLE
Update README.md Issue no #61 Resolved

### PR DESCRIPTION
**Pull request by rajatsinghal02**
I have Updated the Readme File
@soham0005  Please merge the Pull Request with the label attached

### CODE REVIEW

**Review by soham0005 — CHANGES_REQUESTED** [review]
image
For Steps to Install, we do not directly do npm install,
Instead we go to either frontend/backend folder then do npm install
So mention here to go to either frontend or backend then npm install and if frontend is there then mention npm start, for backend, mention node index.js

**Review by soham0005 — APPROVED** [review]

**Comment by soham0005** [comment]
@rajatsinghal02 Good Job! hope to see your contributions again. Happy Coding!

**Comment by AKSHITHA-CHILUKA** [comment]
mention the issue no here

**Comment by soham0005** [comment]
#61

**Comment by AKSHITHA-CHILUKA** [comment]
@rajatsinghal02 
next time mention the issue no 
on the top 
image
here !!

**Comment by soham0005** [comment]
@AKSHITHA-CHILUKA sure!, thanks

**Comment by AKSHITHA-CHILUKA** [comment]
@soham0005 as you are the PA make sure you assign all the open and closed issues and pr's proper labels .

**Comment by soham0005** [comment]
@AKSHITHA-CHILUKA definitely, I'll make a note of it!

**Comment by AKSHITHA-CHILUKA** [comment]
Any doubts you can always tag me or msg in linkedin I will respond

**Comment by soham0005** [comment]
@AKSHITHA-CHILUKA got it!

**Pull request merged**
