### PR TITLE
Updating "Create a Responsive Navbar Section. #23" 

### PR DESCRIPTION
**Pull request by Abhigaba**
Adding register route to the navbar and adding react-router links and update the logo.

### CODE REVIEW

**Review by soham0005 — COMMENTED** [review]
Attach the screenshot of what changes you have made by running the project

**Comment by Abhigaba** [comment]
Screenshot from 2024-10-05 23-26-58
Screenshot from 2024-10-05 23-27-42

**Comment by soham0005** [comment]
@Abhigaba good job!

**Comment by soham0005** [comment]
@Abhigaba Thank you for your contribution to our project! 🎉 Feel free to contribute further and help solve any open issues. We'd love to see your continued involvement!
Happy Coding !

**Pull request merged**
