### PR TITLE
Adding an .env.example file in backend part that helps contributors to understand the code base & also add this to readme also #89

### PR DESCRIPTION
**Pull request by Arnab7456**
@soham0005 please merge it , helps contributors.

### CODE REVIEW

**Review by soham0005 — CHANGES_REQUESTED** [review]
do not directly mention values, instead mention the detailed steps such as create .env file,
set values of MONGO_URL,etc

**Comment by Arnab7456** [comment]
ok working on it & please label it also.

**Comment by PRathod27** [comment]
@Arnab7456 What's the status of the issue on which you are working?
I done, then do commit it, so we can review it.

**Comment by Arnab7456** [comment]
I have already raised a PR and followed the standard way of contributing by not directly mentioning the .env file, but instead using .env.example to help contributors understand the codebase, and I also added this information to the README. I'm still not sure why the PR hasn't been merged.

@soham0005

**Pull request merged**
