### PR TITLE
Feat: Adding ContactUs Backend Functionality using NodeMailer

### LINKED ISSUE #271: ContactUs Backend functionality using nodemailer
When user wants to connect with you via mail then website not support contact us functionality:)

I want to implement a contact Us functionality using nodemailer.

@soham0005 Please assign this issue to me:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #271 Adding contactUs backend functionality using nodemailer:)

@soham0005 Please **assign level-3** because it required alot of code:)

**Testing:)**

https://github.com/user-attachments/assets/cc5aada9-f5f1-45f4-9ce7-b6961fac1ac8

**MAIL**

mail

When onSubmit called then it call to apiConnector:)

UIContact

Api Connector called to backend api by creating axios instance:)

apiConnector

Backend:)
Middleware for contactUs

call

Backend "/contact" recieve post request and called to contactUsController

request

It call to mail sender function using try catch for error handling:)

contactUsController

It create a instance of nodemailer and after call to sendMail function and also render template for recieving mail

mailSender

Mail template:)

template

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@soham0005 Please review it and merge with lable and assign **level-3**.

**Comment by harshbhar0629** [comment]
@soham0005 Please review and merge it with label and please assign **level-3** because it required alot of code.

**Comment by harshbhar0629** [comment]
@soham0005 Please review:)

**Comment by harshbhar0629** [comment]
@soham0005 Please review it and merge with label and assign level-3.

**Comment by harshbhar0629** [comment]
@soham0005 Please assign **level-3** and merge it:)

**Comment by harshbhar0629** [comment]
@soham0005 Please review and merge it with labels:)

**Review by PRathod27 — APPROVED** [review]

**Review by PayalKumari10 — APPROVED** [review]

**Comment by harshbhar0629** [comment]
@soham0005 Please assign **Level-3** it required alot of code.

**Pull request merged**
