### PR TITLE
adding ExclusiveOffers

### PR DESCRIPTION
**Pull request by KGupta2601**
added exclusive offers

### CODE REVIEW

**Review by PRathod27 — CHANGES_REQUESTED** [review]
@KGupta2601 I request you to add the newly added images to move them in the assets folder.
Moreover, change the path as the application is not running.
In ExclusiveOffers. line no 11,16,21,26,31. 
do provide the proper path.

**Comment by KGupta2601** [comment]
@PRathod27 I have made the changes....could you please check once

**Comment by PRathod27** [comment]
@KGupta2601 in Exclusive offers file provide the promotional video to me.

**Comment by KGupta2601** [comment]
https://github.com/user-attachments/assets/ce9a6662-6918-45d4-8a74-c795a5783600

**Pull request merged**
