### PR TITLE
Design new Footer

### LINKED ISSUE #142: Improve Footer Design and Responsiveness
The footer of the Electrokart webpage currently lacks responsiveness and key features that can enhance the user experience.

Suggested Improvements:

Responsiveness: Ensure the footer adjusts properly on all devices (mobile, tablet, desktop).
Essential Links: Add important links such as Customer Support, About Us, Privacy Policy, and social media (Facebook, Instagram, Twitter, etc.).
Improved Layout: Use flexbox or CSS grid for better alignment and spacing of the footer elements.
Social Media Icons: Add social media icons with hover effects to make it more interactive.
Accessibility: Implement aria-labels for links and ensure keyboard navigation works smoothly.
Expected Outcome:

A refined footer design that aligns with Electrokart’s branding, improves user interaction, and enhances accessibility across all devices.

**I am happy to help contribute if needed. Let me know if any further details or designs are required.**

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #142 Design new footer from scratch and also make interactive UI.

footer

@soham0005 Please review my PR and merge accordingly and please assign **level-3**.

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@soham0005 Please assign to me **level-3** because first i edit the footer and make responsive but you want make footer again for the website then i again put alot of time to re-design this footer:)

**Comment by harshbhar0629** [comment]
@soham0005  Please assign to me level-3 because first i edit the footer and make responsive but you want make footer again for the website then i again put alot of time to re-design this footer:)

**Comment by harshbhar0629** [comment]
???

**Comment by harshbhar0629** [comment]
If you required any changes then please mention:)

**Comment by soham0005** [comment]
the footer is very contrast, i'll provide a new design for footer

**Comment by soham0005** [comment]
There are some conflicts, solve and please commit your changes again

**Comment by harshbhar0629** [comment]
> There are some conflicts, solve and please commit your changes again

Conflicts resolve now please merge it with level-3 because first we edit the footer but you said we want new footer then i make new footer from scratch:)

**Comment by harshbhar0629** [comment]
@soham0005 Please review

**Review by soham0005 — APPROVED** [review]

**Comment by harshbhar0629** [comment]
Level-3

**Pull request merged**
