### PR TITLE
Adding LogIn via OTP #151 (Backend Schema and routes)

### PR DESCRIPTION
**Pull request by Abhigaba**
Created a fully functional backend and routes which send emails with otp and verify it and sends a jwt token back like other authentication.

### CODE REVIEW

**Comment by PRathod27** [comment]
@Abhigaba Do record the working of the forget password functionality and share it here.

**Comment by Abhigaba** [comment]
Uploading Feature_rec (1).mp4…


I couldn't  record the sound due to some unknown error with my screen recorder but I tried my best to record it step by step but let me explain what it does, 

1. I have Created a otp schema which stores otp for the required email address and deleted it after every 10 minutes
2. if your comes again it deletes the previous otp in the database and generates a new one throught the api/auth/login/otp route
3.  The otp is matched at api/auth/login/otp/verify route , after successful verification opt is deleted from database and a new jwt token is generated and send to the frontend.  
@PRathod27

**Comment by Abhigaba** [comment]
OAUTH_CLIENTID,
OAUTH_CLIENT_SECRET,
OAUTH_REFRESH_TOKEN

Add these into the .env for the email to work 
you can get these if you follow this "https://www.freecodecamp.org/news/use-nodemailer-to-send-emails-from-your-node-js-server/"

**Comment by soham0005** [comment]
@Abhigaba please add the steps in Readme about the .env content as well

**Comment by PRathod27** [comment]
@Abhigaba Now there are minor changes in the backend. Pull the changes and update your code.

**Pull request closed without merging**
